layout_spectrum: 0.5089605
typography_spectrum: 0.562724
color:
  saturation: 0.4063229
  lightness: 0.3530664
  brandStrength: 0.6164874
  brandColors:
    - '#FA1708'
    - '#0522FF'
    - '#480AFF'
    - '#9876FF'
    - '#A31C62'
  rhythmicContrast: 0.2110729
name: DYAD
